# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13454a7123cabacdc398c7dab136d983"
name = "app-descuento-empleados"
handle = "app-descuento-empleados-1"
application_url = "https://example.com/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
